# +----------------------------------------------------------------------------+
# | CDStore 0.4 * Command line CD catalogue                                    |
# | Copyright (C) 2002-2006 Pozsar Zsolt <pozsarzs@t-email.hu>                 |
# | cdstore_??.msg                                                             |
# | Messages file.                                                             |
# +----------------------------------------------------------------------------+

msg_01=Nincs Xdialog az Ön rendszerén!
msg_02=Nincs elég jogosultsága ehhez a mûvelethez!
msg_03=Lemez név [kilépés: <enter>]:
msg_04=Ez a név már foglalt!
msg_05=Helyezze be a lemezt, majd nyomjon le egy billentyût!
msg_06=Keresési cél (1: könyvtár, 2: archív, 3: multimédia más: minden)
msg_07=Vegye ki a lemezt, majd nyomjon le egy billentyût!
msg_08=Nincs ilyen lemez az adatbázisban.
msg_09=Lemez név:
msg_10=Nem találtam!
msg_11=Lemez név [lemez lista: <enter>]:
msg_12=Az adatbázisban szereplõ lemezek:
msg_13=Használata:
msg_14=Nincs (X)dialog az Ön rendszerén!
msg_15=Fõmenü
msg_16=Keresés
msg_17=Lemez és állomány lista
msg_18=Új lemez
msg_19=Lemez törlése
msg_20=Fontos információk
msg_21=Keresési cél
msg_22=Könyvtárak
msg_23=Archív állományok
msg_24=Multimédia állományok
msg_25=Minden állomány
msg_26=Tartalom -
msg_27=A lemez nem csatolható!
msg_28=Nem találom a szerkesztõt
msg_29=Kilépés
msg_30=Mégsem
msg_31=keresett_szöveg
msg_32=kategória
msg_33=lemez_név
msg_34=Nincs ilyen kategória.
msg_35=Kategóriák
msg_36=A default kategória nem törölhetõ!
msg_37=Kategória [alapértelmezett: <enter>]: 
msg_38=Kategória [kilépés: <enter>]: 
msg_39=Aktuális kategória
msg_40=Új kategória készítése
msg_41=Kategória törlése
msg_42=Az összes kategória
msg_43=Az aktuális kategória nem törölhetõ!
msg_44=Név
msg_45=Nincs lemez ebben a kategóriában.
